Improve build config.

diff --git a/.github/workflows/cmake-windows.yml b/.github/workflows/cmake-windows.yml
--- a/.github/workflows/cmake-windows.yml
+++ b/.github/workflows/cmake-windows.yml
@@ -153,17 +153,17 @@ jobs:
         if: matrix.build_type == 'Release'
         shell: msys2 {0}
         run: |
-          echo "Listing plugins in dist/plugins:"
-          ls -lh "$GITHUB_WORKSPACE/dist/plugins/" || echo "dist/plugins not found"
+          echo "Listing plugins in build directory:"
+          ls -lh "$BUILD_DIR-${{ matrix.gui_framework }}/plugins/" || echo "plugins not found"
           echo "Plugin zip files:"
-          find "$GITHUB_WORKSPACE/dist/plugins" -maxdepth 1 -type f -name "*.zip" || echo "No plugin zips found"
+          find "$BUILD_DIR-${{ matrix.gui_framework }}/plugins" -maxdepth 1 -type f -name "*.zip" || echo "No plugin zips found"
 
       - name: Upload plugins
         if: matrix.build_type == 'Release'
         uses: actions/upload-artifact@v4
         with:
           name: windows-${{ matrix.build_type }}-${{ matrix.gui_framework }}-plugins
-          path: ${{ github.workspace }}/dist/plugins/*.zip
+          path: ${{ env.BUILD_DIR }}-${{ matrix.gui_framework }}/plugins/*.zip
           if-no-files-found: warn
 
       - name: Upload tests artifact
@@ -181,7 +181,7 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
             name: windows-${{ matrix.build_type }}-${{ matrix.gui_framework }}-staging
-            path: ${{ env.BUILD_DIR }}-${{ matrix.gui_framework }}\_staging\**
+            path: dist/staging/**
             if-no-files-found: ignore
 
       - name: Upload installer artifact
@@ -189,8 +189,7 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: windows-${{ matrix.build_type }}-${{ matrix.gui_framework }}-installer
-          path: |
-            ${{ github.workspace }}/dist/packages/*.exe
+          path: dist/packages/*.exe
           if-no-files-found: warn
 
       - name: Upload build logs
